---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
spec:
  releaseName: prometheus
  chart:
    spec:
      # renovate: registryUrl=https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      version: '18.0.0'
      sourceRef:
        kind: HelmRepository
        name: prometheus-community-charts
        namespace: flux-system
  interval: 1m
  install:
    remediation:
     retries: 3
  values:
    grafana:
      ingress:
        enabled: true
        annotations: 
          nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/16"
          kubernetes.io/ingress.class: "nginx"  
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
        - grafana.${SECRET_DOMAIN}
        tls:
        - secretName: grafana-tls
          hosts:
          - grafana.${SECRET_DOMAIN}
