---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: magrathea-fake
  namespace: networking
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    kdns.io/ip-override: 10.0.6.254
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-signin: "https://auth.${SECRET_DOMAIN}"
    nginx.ingress.kubernetes.io/auth-url: "https://auth.${SECRET_DOMAIN}/api/verify"
spec:
  rules:
    - host: magrathea.home.cronuxs.net
  tls:
    - hosts:
      - magrathea.home.cronuxs.net
      secretName: magrathea-tls
