apiVersion: apps/v1
kind: Deployment
metadata:
  name: magrathea
  labels:
    app: magrathea
spec:
  replicas: 1
  strategy: # Need to turn down then turn up (depend on one persistent volume)
    type: Recreate
  selector:
    matchLabels:
      app: magrathea
  template:
    metadata:
      labels:
        app: magrathea
    spec:
      containers:
      - name: magrathea
        image: nginx:1.14.2
        ports:
          - name: http
            containerPort: 80
        resources:
          requests:
            memory: "512Mi"
            cpu: "0.5"
          limits:
            memory: "2Gi"
            cpu: "2"
---
apiVersion: v1
kind: Service
metadata:
  name: magrathea
spec:
  ports:
    - name: http
      targetPort: 80
      port: 80
  selector:
    app: magrathea
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: magrathea
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-signin: https://auth.${SECRET_DOMAIN}
    nginx.ingress.kubernetes.io/auth-url: https://auth.${SECRET_DOMAIN}/api/verify
spec:
  rules:
  - host: magrathea.${SECRET_DOMAIN}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: magrathea
            port:
              number: 80
  tls:
  - hosts:
    - magrathea.${SECRET_DOMAIN}
    secretName: magrathea-tls
