---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authelia
spec:
  releaseName: authelia
  chart:
    spec:
      # renovate: registryUrl=https://charts.authelia.com
      chart: authelia
      version: 0.5.6
      sourceRef:
        kind: HelmRepository
        name: authelia-charts
        namespace: flux-system
  interval: 1m
  install:
    remediation:
      retries: 3
  values:
    # https://github.com/authelia/chartrepo/blob/master/charts/authelia/values.yaml
    domain: "${SECRET_DOMAIN}"

    pod:
      kind: Deployment
      # deploymentStrategy: Recreate # Not supported. Likely to fail during update
      annotations:
        backup.velero.io/backup-volumes: authelia

    # Persistence of /config
    persistence:
      enabled: true
      existingClaim: authelia

    # Login ingress
    ingress:
      enabled: true
      subdomain: auth
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        kubernetes.io/ingress.class: nginx

    configMap:
      theme: dark
      default_redirection_url: "https://home-assistant.${SECRET_DOMAIN}"

      # authentication methods
      authentication_backend:
        ldap:
          enabled: false
        file:
          enabled: true

      # Track sessions
      session:
        expiration: 4h
        inactivity: 30m
        redis:
          enabled: false

      # Persist sessions
      storage:
        local:
          enabled: true
        postgres:
          enabled: false

      # Notify (password reset)
      notifier:
        filesystem:
          enabled: true
        smtp:
          enabled: false

      # The Rules!!! 
      access_control:
        default_policy: deny

        networks:
        - name: home
          networks:
          - 10.0.0.0/8

        rules:
        - domain:
          # iot
          - "home-assistant.${SECRET_DOMAIN}"
          - "esphome.${SECRET_DOMAIN}"
          policy: bypass
          networks:
          - home

        # At Home
        - domain:
          # kube-prometheus-stack
          - "alertmanager.${SECRET_DOMAIN}"
          - "grafana.${SECRET_DOMAIN}"
          - "prometheus.${SECRET_DOMAIN}"
          # Media
          - "bazarr.${SECRET_DOMAIN}"
          - "calibre.${SECRET_DOMAIN}"
          - "jackett.${SECRET_DOMAIN}"
          - "plex.${SECRET_DOMAIN}"
          - "radarr.${SECRET_DOMAIN}"
          - "sabnzbd.${SECRET_DOMAIN}"
          - "sonarr.${SECRET_DOMAIN}"
          # IOT
          - "home-assistant-vscode.${SECRET_DOMAIN}"
          - "node-red.${SECRET_DOMAIN}"
          policy: one_factor
          subject:
          - "group:admins"
          networks:
          - home

        # Away
        - domain:
          # kube-prometheus-stack
          - "alertmanager.${SECRET_DOMAIN}"
          - "grafana.${SECRET_DOMAIN}"
          - "prometheus.${SECRET_DOMAIN}"
          policy: two_factor
          subject:
          - "group:admins"
