---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authelia
spec:
  releaseName: authelia
  chart:
    spec:
      # renovate: registryUrl=https://charts.authelia.com/
      chart: authelia
      version: '0.4.19'
      sourceRef:
        kind: HelmRepository
        name: authelia
        namespace: flux-system
  interval: 1m
  install:
    remediation:
      retries: 3
  values:
    domain: "${SECRET_DOMAIN}"
    configMap:
      # authentication methods
      authentication_backend:
        disable_reset_password: true
        ldap:
          enabled: false
        file:
          enabled: true

      # Track sessions
      session:
        redis:
          enabled: false

      # Persist sessions
      storage:
        local:
          enabled: true
        postgres:
          enabled: false

      # Notify (password reset)
      notifier:
        filesystem:
          enabled: true
        smtp:
          enabled: false

      # The Rules!!! 
      access_control:
        networks:
        - name: home
          networks:
          - 10.0.0.0/8

        rules:
        - domain: "2048.${SECRET_DOMAIN}"
          policy: one_factor
          networks:
          - home
          subject:
          - ["group:admins", "group:moderators"] # OR
          # AND
          - "group:dev" 

    # Persistence of /config
    persistence:
      enabled: true

    # Login ingress
    ingress:
      enabled: true
      subdomain: login
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        kubernetes.io/ingress.class: nginx
