---
apiVersion: v1
kind: Secret
metadata:
  name: storage-secret
type: kubernetes.io/iscsi-chap
data:
  node.session.auth.username: ${SECRET_STORAGE_CHAP_USERNAME_BASE64}
  node.session.auth.password: ${SECRET_STORAGE_CHAP_PASSWORD_BASE64}
