---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-red
spec:
  interval: 1h
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: node-red
      version: 9.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    # Backup
    podAnnotations:
      backup.velero.io/backup-volumes: data

    image:
      repository: nodered/node-red
      tag: 2.0.5
    env:
      TZ: "${SECRET_TIMEZONE}"

    # Pod
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "1"

    persistence:
      newdata:
        enabled: true
        existingClaim: node-red

    initContainers:
      copy-config:
        image: nodered/node-red:2.0.5
        command: ['sh', '-c', 'cp -R /data/* /newdata/']
        volumeMounts:
        - name: newdata
          mountPath: /newdata
        securityContext:
          runAsUser: 0

    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: letsencrypt-production
          nginx.ingress.kubernetes.io/auth-signin: "https://auth.${SECRET_DOMAIN}"
          nginx.ingress.kubernetes.io/auth-url: "https://auth.${SECRET_DOMAIN}/api/verify"
        hosts:
        - host: node-red.${SECRET_DOMAIN}
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - node-red.${SECRET_DOMAIN}
          secretName: node-red-tls
