---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: uptime-kuma
spec:
  releaseName: uptime-kuma
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: uptime-kuma
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  interval: 1m
  install:
    remediation:
      retries: 3
  values:
    # https://github.com/k8s-at-home/charts/blob/master/charts/stable/uptime-kuma/values.yaml
    image:
      repository: louislam/uptime-kuma
      tag: 1.16.1

    env:
      TZ: "${SECRET_TIMEZONE}"

    podAnnotations:
      backup.velero.io/backup-volumes: data

    persistence:
      data:
        enabled: true
        existingClaim: uptime-kuma

    service:
      main:
        ports:
          http:
            port: 3001

    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: letsencrypt-production
          nginx.ingress.kubernetes.io/auth-signin: "https://auth.${SECRET_DOMAIN}"
          nginx.ingress.kubernetes.io/auth-url: "https://auth.${SECRET_DOMAIN}/api/verify"
        hosts:
          - host: uptime-kuma.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - uptime-kuma.${SECRET_DOMAIN}
            secretName: uptime-kuma-tls
