---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: uptime-kuma
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
    - networking
  selector:
    matchLabels:
      app.kubernetes.io/instance: uptime-kuma
  endpoints:
  - basicAuth:
      password:
        name: uptime-kuma-auth
        key: password
      username:
        name: uptime-kuma-auth
        key: user
    interval: 15s
    port: http
    scrapeTimeout: 10s
