---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: uptime-kuma
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
    - networking
  selector:
    matchLabels:
      app.kubernetes.io/instance: uptime-kuma
  podMetricsEndpoints:
    - port: http
