apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: stash
spec:
  releaseName: stash
  chart:
    spec:
      chart: stash-community
      version: '0.14.1'
      sourceRef:
        kind: HelmRepository
        name: appscode-charts
        namespace: flux-system
  interval: 10m
  install:
    remediation:
      retries: 3
  values:
    license: ${SECRET_STASH_LICENSE}
