apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: intel-gpu-plugin
spec:
  releaseName: intel-gpu-plugin
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: intel-gpu-plugin
      version: 4.3.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  interval: 1m
  install:
    remediation:
      retries: 3
  values:
    # No need to deploy it on Arm machines.
    nodeSelector:
      kubernetes.io/arch: amd64
