---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx
      version: 4.0.19
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx-charts
        namespace: flux-system

        # annotations:
        #   metallb.universe.tf/allow-shared-ip: "ingress-address"
  values:
    # https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/values.yaml
    controller:
      ingressClass: nginx
      replicaCount: 1
      service:
        type: LoadBalancer
        loadBalancerIP: "${INGRESS_NGINX_LB}"
        externalTrafficPolicy: Local
        annotations:
          metallb.universe.tf/allow-shared-ip: "ingress-address"
      config:
        ssl-protocols: "TLSv1.3 TLSv1.2"
        proxy-body-size: "100m"
        use-forwarded-headers: "true"
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          additionalLabels: 
            release: kube-prometheus-stack
      resources:
        requests:
          memory: 100Mi
          cpu: 100m
        limits:
          memory: 500Mi
