apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# Namespace always comes first
- namespaces
# Priority
- monitoring
# Other systems
# - backup
# - cert-manager
- intel-gpu-plugin
- logging
- metallb-system
- networking
- reloader
