---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: radarr
      version: 13.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  install:
    remediation:
      retries: 3

  values:
    # Backup
    podAnnotations:
      backup.velero.io/backup-volumes: config

    image:
      repository: linuxserver/radarr
      tag: amd64-version-3.2.2.5080 

    env:
      PGID: '1000'
      PUID: '1000'

    podSecurityContext:
      # runAsUser: 1000
      # runAsGroup: 1000
      supplementalGroups:
      - 100
      # - 568

    initContainers:
      update-config-ownership:
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /config"]
        volumeMounts:
        - name: config
          mountPath: /config
        securityContext:
          runAsUser: 0
      update-config-permission:
        image: busybox
        command: ["sh", "-c", "chmod -R 774 /config"]
        volumeMounts:
        - name: config
          mountPath: /config
        securityContext:
          runAsUser: 0

    # Pod
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "250m"

    # Persistence
    persistence:
      # Make sure it has pid/gid 568
      # and it is pre-populated
      config:
        enabled: true
        existingClaim: radarr
      downloads:
        enabled: true
        existingClaim: download
        mountPath: /downloads
      movies:
        enabled: true
        existingClaim: movie
        mountPath: /movies

    # Network
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        hosts:
        - host: "radarr.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "radarr.${SECRET_DOMAIN}"
          secretName: radarr-tls
