# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:KAjaDSWrwGtY8iV71ouzYQ==,iv:Q74sf45UVO8XaSGQhEpxKw3Z99186/YUkPX2z7hEMVU=,tag:I8gm988/v8jyssyLWvXoPA==,type:str]
    SECRET_LETS_ENCRYPT_EMAIL: ENC[AES256_GCM,data:77iR04MCjcP4Ig96/Aremj4=,iv:km1PX4/8EeTNH0ZKvRMS/4SAl25I+ZYq4/+Cq7uliE8=,tag:sRVe8KdSHKNHpJGcCxpUVA==,type:str]
    SECRET_TIMEZONE: ENC[AES256_GCM,data:tVJYPUwuDPIZ28TGcQ==,iv:igWKRE/a3lCGu3qvoiv010420cP//E3WSeQvLqPGgPM=,tag:wDY7EYRghEWl4HScT9BE4g==,type:str]
    SECRET_IQN: ENC[AES256_GCM,data:WCgXYzTZciRvHjvVN7YAx5kQ5wrxSrRo,iv:+YPERGwjBdgGjPzN+7a6LgX3DaNPT3k33r/cVNGBg1I=,tag:fNP4IZ74PtyiCU5DrQigtg==,type:str]
    SECRET_STORAGE_ADDRESS: ENC[AES256_GCM,data:9fKELhoRl5WIgA==,iv:puSiOcpjAFeYovfb+aU3vfLrYVYFQyW4/Bymu44Nxxg=,tag:Bp74XH7vIpaqUy3MawORww==,type:str]
    SECRET_CHAP_USERNAME_BASE64: ENC[AES256_GCM,data:KbT/03+DofE=,iv:U2HzN41reekU7W12plhD/GeVJNFJCKtpGX4QCzS6A9M=,tag:qy9DfWzQNYw1rBwh1ofGOQ==,type:str]
    SECRET_CHAP_PASSWORD_BASE64: ENC[AES256_GCM,data:mFC/4ojikoTTiOQZvWZk3A==,iv:R3cBrtJYUPfGMGZKakmgr/ydV97xvLT3fB3PjC41wuQ=,tag:niZWdhJcj+GBL/zh453JZQ==,type:str]
    SECRET_VELERO_BUCKET: ENC[AES256_GCM,data:lAzKaMct0eWBS3PA,iv:sK8FrcgK526SSoHkLQsZnABKDsmBSJNWiPsPDLvRPBY=,tag:HtDijEW/1vQ3qp2UDRqkaw==,type:str]
    SECRET_FLUX_WEBHOOK: ENC[AES256_GCM,data:Fc7hN6VvWuekx4dv5jBuEdEukQPL7IQ5l5ITtsgvoGphgXDt283Snq0KRUq1HZ4FXbTqvJrX4KNn9HTG4dHen0qHlLtS0J51cNikbAAfTb00Iq97Ly4YR/jjeuStYXE+W3F8bLDRV/rcosmK0DhqkMD0fL1FzTP9kFD3TUDX8Go3YGlmRN+QVui7WOuA1KR/zghFxiYFPY+2zTZiCMvDAB+BvZ1ryqdt,iv:NOYlbdv7odT+K++M0AjP0v17y5yCRUMFN9Vu0gy4qN8=,tag:Q4nuMUfIU0DreChA1X7J3g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-08-21T17:16:40Z"
    mac: ENC[AES256_GCM,data:wgnyr31Eybod91fo4MPwWp+MlInq6r+ghdOkodp6DxbZDcfL1VVcV8l7C++xvfILchAxwtYDv9IH1JOyWz44cqhnSISAw8wWD/qCTD4rvY4xwrZa56a7wh/tp9O74IrXXawOf2Woph2LwUHh57gNshhzEEJ68+xO2ycBlV6DSD0=,iv:45eMVqaDyTbl4K6+jx0ICmjSKMyoTALkgnCjey+E/yA=,tag:WGSYFO2yDEi/UPf8hmO/EA==,type:str]
    pgp:
        - created_at: "2021-08-07T18:25:41Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA+xZIdjAexkpAQ/8D/ohLwXLwNepFrYWlXiKfcMie7BcNJLiepSdNESu7l7t
            vNEELCtuFQryL/0aha6r5WqA3an+bqQ4tnQSKsx8YJbJHvUH5yrKX+/t0B8RBmk1
            c4fs1G7zEWxCkRtmMTtLeoT8fEtQ+lrjkea8cmYWeorop2Ey0NtoNNIumLbQwz9X
            TSW+AjXpXLnUT0DW9vWBX6UT9qeFuSsZitYMd6qTxV8BzUvoAYM7shNj7qmzffBu
            ce4J26UKjRqA9nVhT6YoOd8Mm48Qwnf903MN+Hch8Y6q0UYPgK+jgrE7P+4oiNm3
            10naxT/VIIESk1r/H1MPn9B69XtAMtRa6PSvhwsaFivU0Tu5VT3577bJD12FrQyX
            dN9/8riLkxz36D5iRTC68IVlUevepIAwr3F7FWfxBnSppIy9a+U9plD75szzb8mM
            de/IPWyOohPmfv48gG/IecYkVH2PV0EJSjXlmlLYngFz4yC7olT4nxaskcK6T/HI
            FDiboa/1uUX2wlUDUkRPNu7iFS77P6jCkRKGVY2FsUFR1FTEazmvuMiaXtrkdk7H
            VeLtFAD+oYcZj51eiyapCU+Dtt7slQQZQNtAPDLW5isZByuxFqK7QUoVsQpHePn/
            +53KDyAIp3sf4JikwnotmY0z25pi7/ZvGXx07QeLnS4InnalpNPTIj5lGdIglcrU
            aAEJAhVhBJDEF3H/E8m3FVXCyTvE61V7e+IbbLgXyqMUc+nQd3gn+Vvwhd25ZMog
            QrQfxhFQeAfBYXqtaaBW4YnieBjxEpVNNZDNHaEdDualovv2egPqSHWSem3D23V2
            Y2hQJ804aMUO
            =rT+g
            -----END PGP MESSAGE-----
          fp: CC26950EB0DB08F2B4D016B83F8C0A0F531AA043
        - created_at: "2021-08-07T18:25:41Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA2+v8WHLsAdpARAAv+uzZHRtOkNvJhDlGQ+KMjz/GSh/OvHDGjwWXMhMOnxV
            11q4qQIsT06K2mztWhhAxNy3B065ufmB+7FtWnTHLFieW8RYQLwS+i/Ub68TLVfc
            wK0Rnpfm/zS4hmU534SiL3nDeMwrILoF1vgJbUEuTrPpQZGY/IjFHVb0udmpLnZz
            xDvMYQidBPraNINLtgNl4SWbROvr0USGCiDi4Gm42K+BC0lowFp55bVJG0DYjyHC
            eNsjRkIz5YS3sxL6OFrMgFdt8QMVqMJcoFP67CJGcMpoyY0L7c0cudm7zR7ff7Qd
            oHJkyngyNQXqVtuaaBVEqdvbotdzRdYd+PFQAanlkqtCKqeduEbHhcTHGNgvocwm
            VSNeuUkEbNKYAbAi7R73hbyT3lcuoB4EPOqCl4gpXU2JdkQGmfPFdKSKHgCNMkQ/
            XkoWG0l8Pwm7foDt/R6fWIawl+Hiaem6AIi4EJVluoWh7epqX9MtPox/fUrJ38pn
            czo+yIXo7uXK6nZO+L/T8rT3IW77BrJyEF2drEX+updltTNN9dCw/aqgRRx9H2+D
            r4sVHL9a6rJSxaDoRW/1x1u15+DcMVmKSLNq6bXP9g/Uc1jY2j+/+TCBxOD6yrLy
            W9brcN8C4AoPgf32kFRw8HzKHRho7NaUR9vZH+SZj7w6FGHkA4zRrA1lDarcltnU
            aAEJAhUrNdUF4VZvrHw45zf25Jq3YfglliUGkHj/3oz3ImI3oRP9pmt8VxnU+HOD
            /Wt7fgK+Pl2wH7GzwX7u3fcXSDKqAPoiIEkkBpj35X3Z8uZVKGITc1KfOuxZcTxx
            0kU+hNMn4atc
            =VgMo
            -----END PGP MESSAGE-----
          fp: A62A6E10823351A34290734E93DBA1E6E6124250
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
