# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ALERT_MANAGER_WEBHOOK: ENC[AES256_GCM,data:h1qfQdjnvr1PRDHFSHeh2GIdLYg1ifwaZ2MGVGdUWCq1AhDzP4a1LYtirGbScBevl0pUYQkr4TyV5r6UnjZDm0ldsTKsCLcDmrhrFO6bypG8II9ZBy5RtuxahaYQv9A2t4B4bSj9/euLaKzr6UiNMYh0SKFvilogIP6VEO3s,iv:Rq5vqQqx+3AS3lIr4/X+dFULoJkWPYj7UfdlMwHkZY4=,tag:83baxMIFpTrzNYajJr24EQ==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:KAjaDSWrwGtY8iV71ouzYQ==,iv:Q74sf45UVO8XaSGQhEpxKw3Z99186/YUkPX2z7hEMVU=,tag:I8gm988/v8jyssyLWvXoPA==,type:str]
    SECRET_FLUX_WEBHOOK_BASE64: ENC[AES256_GCM,data:9NQAPPDYxpfViR8Q9r5jqzrSluSG96Mrgh36NuXLuhrMlPGWA8usStM3vnWqMiSTTkuDa3uc+CeITixXGllazZO2ulOkRuTTC1dtEvC68Zg/VLglQfG3NscZ0s9rji0EUg/9FA/T9pk8fOWlPv5pQPUHPN6aoJobKHjx1QM89/lZJnOnv/Sy2ckRQ6Xdrg/zhV4K0DsOqc8+WLTMH1TUTkQIGT9yeiSA,iv:p09uGVVH6UDtLHmYwTclu/Dsp7wTe+F8wIBNBZyZzDc=,tag:wJW+j4kEociwbIOSGpqwQQ==,type:str]
    SECRET_LETS_ENCRYPT_EMAIL: ENC[AES256_GCM,data:77iR04MCjcP4Ig96/Aremj4=,iv:km1PX4/8EeTNH0ZKvRMS/4SAl25I+ZYq4/+Cq7uliE8=,tag:sRVe8KdSHKNHpJGcCxpUVA==,type:str]
    SECRET_STORAGE_ADDRESS: ENC[AES256_GCM,data:9fKELhoRl5WIgA==,iv:puSiOcpjAFeYovfb+aU3vfLrYVYFQyW4/Bymu44Nxxg=,tag:Bp74XH7vIpaqUy3MawORww==,type:str]
    SECRET_STORAGE_CHAP_PASSWORD_BASE64: ENC[AES256_GCM,data:D9eh7b9yYeXhe0dxt1orQA==,iv:bqXv+rMGy+uYFaYq2Y7NlPbeosdOODa4rgVmMfwPsfA=,tag:pYgzd9gxaGk1c0NbUnhT/A==,type:str]
    SECRET_STORAGE_CHAP_USERNAME_BASE64: ENC[AES256_GCM,data:DRjhE3Hvy2w=,iv:01FmEd7hAwK31o8PnkBd3yOry2hz7nr31pBPLcMiRRE=,tag:ndWTahXSNW1RX0CGT5vdDw==,type:str]
    SECRET_STORAGE_IQN: ENC[AES256_GCM,data:TJ8fhc2nkwqG45KC/khDmr+cYd3YVtFH,iv:oraN83t7Mp3CW5GUXIzwzqVvHpRgMYzg+6z0X+K1NlY=,tag:sfPidBgJyM3YV21kmH+bfw==,type:str]
    SECRET_STORAGE_NFS_SERVER: ENC[AES256_GCM,data:CIbBNhOxYSWBBw==,iv:tTGdijq0tHkwVIe7L3pt1akUkH30TUbtlBtUvgdE6ko=,tag:s0FvReU/A/q9JfnetZicmw==,type:str]
    SECRET_STORAGE_NFS_PATH: ENC[AES256_GCM,data:/w52aGDHsl20gMbKNSYpEQ==,iv:jtDmrkLPQmilfKuSUjcrf/WXtTqoP6IkywKUQU3ekOk=,tag:zlKGo8aEdupk4VMWJa//dw==,type:str]
    SECRET_TIMEZONE: ENC[AES256_GCM,data:tVJYPUwuDPIZ28TGcQ==,iv:igWKRE/a3lCGu3qvoiv010420cP//E3WSeQvLqPGgPM=,tag:wDY7EYRghEWl4HScT9BE4g==,type:str]
    SECRET_VELERO_BUCKET: ENC[AES256_GCM,data:lAzKaMct0eWBS3PA,iv:sK8FrcgK526SSoHkLQsZnABKDsmBSJNWiPsPDLvRPBY=,tag:HtDijEW/1vQ3qp2UDRqkaw==,type:str]
    SECRET_ZIGBEE2MQTT_PASSWORD: ENC[AES256_GCM,data:Iw9P4Fdtk0MbkIJg8pY=,iv:aYD4n0NBAlvo5UyDLzzMMaJc7Lbr7qnonP0EVG9SQxw=,tag:BNFqd3hE29bCzcv4s/w3cQ==,type:str]
    SECRET_ZIGBEE2MQTT_USERNAME: ENC[AES256_GCM,data:nhteqsOY,iv:Tw+vT2/FOPntZcSz4NGRrZj+Fl59IXZkWloXTU3f/d8=,tag:2y+U1hhX5XR9LkSgfY4msg==,type:str]
    SECRET_VAULTWARDEN_CLIENTID: ENC[AES256_GCM,data:zV66lXE=,iv:lilQBBYzrkw3aTFXe7hqlagZRgWDK5RZNQZ9Rc9U8z4=,tag:izOK8U9zfJg4Qxx+kJPO/g==,type:str]
    SECRET_VAULTWARDEN_SECRETKEY: ENC[AES256_GCM,data:fYUEBkpRQitX+AJHbznIVmH5MyolTsfL/5ze,iv:03p664+gLfeLKtPh1oWrlneMt7vwXczzhRhUIzuVpG0=,tag:R2nnH8NFHEegMI1mOhtzZA==,type:str]
    SECRET_OVPN_1_PASSWORD: ENC[AES256_GCM,data:WPctaSn3KVE0HW5sOHbkEJAhWb7M5oc7xGPxreRi/cSruQ==,iv:dnWKsSCQoANsG2/tJ2IrZR6d5j96cDjtyCuUbuqngiI=,tag:r6p6xSQV8z9woKHr0+/zYw==,type:str]
    SECRET_OVPN_1_CONFIG: ENC[AES256_GCM,data:ZpTCK2fOJlOcALitqlEuhB/DFE/DrWjCjcsY21NbpOo4MOQhUBedcQimZcZKsqFFdgH+CYvk8LDRKTJnd9JjFyVxSWrDFCymyjPEVxMGP5qSRroLrj8lru1g1RjYC2f/Hvj2+Drm+KouSIgxLXBoU63XiZRz4QhTlCGSwxx42vcTaDjIrdvK/cdqZFbbuYq7gIHE+jMJRPABDXbamDokMDt9GyPfQYqk8INpZwoC963GBqUjYamKV6fxZgM72QsX+UHXrX8gDqt/vttBIk02QQ2/OJ5uRymq6usTGhTyYX4NP/MOaqk0vgI2CoVEZN3vv8GFlJJ1sjfdY/tvHI/USuwQlYtCo2UtsHXoJU1qm5b7vZICArP8wNHYXUefE/TCD9RNdaR6eWeTg+vbUYUsKwJyVTKEwiRXaRbRqvyoLdQ6neWORaRYqpLkpBuVU4YH2yt4pK/cjt2wQ1dHXRRCHdVXT/kdZM1uBkN0YBxeYfOWJQa94/ajMOeV7I4JMq2NBwvSlfnTVS7+AQitYvo290t8JAa3RLjPhDF42lqOmGWlHMuA8XN3XpumdLDMmMQ5+Klh+dRfeKvkD4NhhAnK4IVyVhJ3t4MrCiVVA4tukjZfZe/lC14yFFA+yu6qoUjgYTVR2mCG5MRgiWlvEdlbzJPZi+6m82eyvb+/s+Rqdrc9Dyr3t/26QWkzI5U2gm5+FUVi1YR2ox9rmx4D19l79C5zQnIcQ3kw+C+LuWlZaEHJqqvOK0eOBabdrXwpUY+eOXAwv5UYLuMwajGg7HE/6LT23hZWskSnvowwzHaZNoq6rAXWEn358qV3noEAcAIOhY1HXIS2J9PockTQpCCB6cYGncZHZ2CacWEyMC5t3BLBSD071/i7GHWKzGuEM1LGF/f/heV3rhyrcJw0a4lYmg1zxr6Md8W2qSkUAnB8C9h5AmY+uHY3t5COX3ka2s+cD19/GoSq/Izh7FpdiI4+C9sYWxPtyo2k/7XE4HEW4ENZ5usAvXiFDNiVA/UDV2RZG95xxTx1gN7THiftVFEuklIYfvVJ0inPtTs/duWUi+PQmDfOfIxq+HANrJb70dNeF4iMYE2ctKYvlJU3shgB5O1fA/QTJ6x57NRQA3lTa9pYVwj2IzspL9b3XMf7XqEqOMKxped1+SUUgyLgIzsErOGjdRP63qML6GPtDkvlkgfEuK1VjpwpX6mXoXE8h284lnkE66c/g2Gb5B1XXu0bA8GGDmGriqwKzt5TBG2FG8l1CzB4FiMS5eyiet9NLOBxtBMNdOqc1w5zq3a1irqRFT8hoQQhXLNHmNdvpJClFWBtK9YZKC5Oe6F7Q2rfo+zKdWUGA3Ie11q1HDHqHkNVLDGbpZ5CNunKWRLHP1W7WgYvDa68OyxBSHSL9d3CBtsSqR2miq1fmMQYQlveH+Md06GkWn6Xgaub7TMO9BsiwKfZRz55qHpyRIEx/T7pqIL9FjvLVonb+M+1qi+xoOFnoANdu4xowhnf/pzobN4LHQmALE5D0nvl0CGIzg5knfPhvaVmtNr8n4ZiOrWChB3kxJ7OWoj9v+1lCwN6DVWNZjI28PPYTAcugrKZkvO9aBG9vrH7pJXxWOfi9BMBvecb0oT8Yr8mN2TDTxqRmckwLowKgpjr8l7YSfTwwfJ/lnytOehn5GjZoxU4Xi+coZa5PikFXBasca+uDNhNIxOJUdbs9TobkcmGQQkVCggdAvZZQqA39+hq1Op+S52PzE3REluBIyzHuaGV6skONIwmBmOQ6YgMApPtstEe3oI3G0rVic+Z6pxOhPFwf/CQhpoj9PstfO0nIU8ljZaOP50aDa++MM7Dr0LDrdNq9Z1mQwNt/+RqmhruQtD4dsKYh97nQJQMFCAyOXrbIo/Hee4rjCQUV2b4Wyph0DZkJpgr6ypv5s/7ggJpsW8gFeTfvoWAnDvUmIObVhrAqMcWQLYR94alhG6yOh2TUzocIK9nbA2ACY4AiirUjJjoN/Y3NpYGl+BwNLs9bWi+oNGcwJIViwjXUjZ1U0cqxYPEOLS964pkNZLfwDYoufhLqHKwE87V1RpvZi+YgLG6QKBAJv5FNcnACqMDjUX8XL5YtM6lvcRJRgXDV04p/3vkMC1oZXt26iZJEaECtbQ55AeJvBdyQisAQFy+ms+jF2V9ZPLsvITUat9VqyhIpZfMB0sA9ANUS4QWyXy4oZUm0ttn2rhEbsExwHMHTBUVYDB6cq9IEl5d3KFZfXBeqzVI5Iww0/byJouUAxkslmZRstTeaLEWKq3wk9epHHRBSI+OR0Crjqh47TMvegLte8XCTJ+xC855RH+AbdtI60KS5A7qViUGo1R/exGoX+PlhQD8MvdFEJT8+Hv0A0Dj8VMK9LffBevvIjTy/c6XKgIgQZ4HeeeXzF2at/f16ihDWjUEEAolgJ5W2lhy6NYHPFNj/akbl5v7KfJhxr6WUNVMcw2/n/Ks4JhWzRquPUa5U9OG2C7n8vWIP/uDpirhbHz9WUSow379MpDfX5Al+/G/WGr+Jw6EH8Img85e/COrr4+4LsYccR0LXDY2mzCLeO4T9rI9xSJWYX7EfWdajS9bRWmd8VxtKkaxOyy4UJozeQTqfHv07FWVMbZkv4lqukeOn5QPgr5sWYEu4Lvfgd7/P9H+aP1+oNbxwGa7BCkKSkG9b3f76tPJ8MFkFEu2/fdCr2/7B4r3OS6j+uB1/uloy2yRRlrwmKiqbMUORjI1Jttn2NTi62KXFQFctrxMoDAfJpRehoXqYx6f2yoNTKiM0/0HlC3VlSE7LR6UOXiWP/kRknpmT3xy8Zdr5ndLeZaZJ5iOZjFzhYpVrW6LodBxPSxXNlVtpUEhCJLSOcT17S26RqNAjWftI2woBSjgYLSoSx+dxyBXurAktvitlpQhDBMj7FoSAX7ngClgCVNhQwKK8Eno,iv:KZnkerXHV+O47AKiaGRHuR9XwS9pn8p9NN7u3XcwpUI=,tag:bN0F5z+EzErzGGTA/5da1A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-08-25T16:36:27Z"
    mac: ENC[AES256_GCM,data:mgGhGAd/Lc9I2Pb0BUFlHfp3Fd7KI9Z3I9KjAPdmwomPVlKRHD9ANBsh5puB5/mLYQ8hnEBLs8F+ktqGqyGEK0/dCDM6SBSY6uKDBSx4B2VpgmUYhr9XbsI0zdvN1TxZ6UKQYt12xPyyMqETF1ZDQ2kjriNHP+n5ySzI/VNXBMM=,iv:EBa9sdsDV8mxWUPRp70ZHEs6z4lpVWoYk6UJWiHuzLo=,tag:0yfBVZOXGpncMDkE3cU58w==,type:str]
    pgp:
        - created_at: "2021-08-07T18:25:41Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA+xZIdjAexkpAQ/8D/ohLwXLwNepFrYWlXiKfcMie7BcNJLiepSdNESu7l7t
            vNEELCtuFQryL/0aha6r5WqA3an+bqQ4tnQSKsx8YJbJHvUH5yrKX+/t0B8RBmk1
            c4fs1G7zEWxCkRtmMTtLeoT8fEtQ+lrjkea8cmYWeorop2Ey0NtoNNIumLbQwz9X
            TSW+AjXpXLnUT0DW9vWBX6UT9qeFuSsZitYMd6qTxV8BzUvoAYM7shNj7qmzffBu
            ce4J26UKjRqA9nVhT6YoOd8Mm48Qwnf903MN+Hch8Y6q0UYPgK+jgrE7P+4oiNm3
            10naxT/VIIESk1r/H1MPn9B69XtAMtRa6PSvhwsaFivU0Tu5VT3577bJD12FrQyX
            dN9/8riLkxz36D5iRTC68IVlUevepIAwr3F7FWfxBnSppIy9a+U9plD75szzb8mM
            de/IPWyOohPmfv48gG/IecYkVH2PV0EJSjXlmlLYngFz4yC7olT4nxaskcK6T/HI
            FDiboa/1uUX2wlUDUkRPNu7iFS77P6jCkRKGVY2FsUFR1FTEazmvuMiaXtrkdk7H
            VeLtFAD+oYcZj51eiyapCU+Dtt7slQQZQNtAPDLW5isZByuxFqK7QUoVsQpHePn/
            +53KDyAIp3sf4JikwnotmY0z25pi7/ZvGXx07QeLnS4InnalpNPTIj5lGdIglcrU
            aAEJAhVhBJDEF3H/E8m3FVXCyTvE61V7e+IbbLgXyqMUc+nQd3gn+Vvwhd25ZMog
            QrQfxhFQeAfBYXqtaaBW4YnieBjxEpVNNZDNHaEdDualovv2egPqSHWSem3D23V2
            Y2hQJ804aMUO
            =rT+g
            -----END PGP MESSAGE-----
          fp: CC26950EB0DB08F2B4D016B83F8C0A0F531AA043
        - created_at: "2021-08-07T18:25:41Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA2+v8WHLsAdpARAAv+uzZHRtOkNvJhDlGQ+KMjz/GSh/OvHDGjwWXMhMOnxV
            11q4qQIsT06K2mztWhhAxNy3B065ufmB+7FtWnTHLFieW8RYQLwS+i/Ub68TLVfc
            wK0Rnpfm/zS4hmU534SiL3nDeMwrILoF1vgJbUEuTrPpQZGY/IjFHVb0udmpLnZz
            xDvMYQidBPraNINLtgNl4SWbROvr0USGCiDi4Gm42K+BC0lowFp55bVJG0DYjyHC
            eNsjRkIz5YS3sxL6OFrMgFdt8QMVqMJcoFP67CJGcMpoyY0L7c0cudm7zR7ff7Qd
            oHJkyngyNQXqVtuaaBVEqdvbotdzRdYd+PFQAanlkqtCKqeduEbHhcTHGNgvocwm
            VSNeuUkEbNKYAbAi7R73hbyT3lcuoB4EPOqCl4gpXU2JdkQGmfPFdKSKHgCNMkQ/
            XkoWG0l8Pwm7foDt/R6fWIawl+Hiaem6AIi4EJVluoWh7epqX9MtPox/fUrJ38pn
            czo+yIXo7uXK6nZO+L/T8rT3IW77BrJyEF2drEX+updltTNN9dCw/aqgRRx9H2+D
            r4sVHL9a6rJSxaDoRW/1x1u15+DcMVmKSLNq6bXP9g/Uc1jY2j+/+TCBxOD6yrLy
            W9brcN8C4AoPgf32kFRw8HzKHRho7NaUR9vZH+SZj7w6FGHkA4zRrA1lDarcltnU
            aAEJAhUrNdUF4VZvrHw45zf25Jq3YfglliUGkHj/3oz3ImI3oRP9pmt8VxnU+HOD
            /Wt7fgK+Pl2wH7GzwX7u3fcXSDKqAPoiIEkkBpj35X3Z8uZVKGITc1KfOuxZcTxx
            0kU+hNMn4atc
            =VgMo
            -----END PGP MESSAGE-----
          fp: A62A6E10823351A34290734E93DBA1E6E6124250
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
