---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: esphome
  labels:
    role: alert-rules
spec:
  groups:
  - name: esphome
    rules:
    - alert: esphomeOverheating
      annotations:
        message: ESPHome node {{ $labels.name }} has {{ $value }} °C of temperature.
      expr: |-
        esphome_sensor_value{unit="°C"} > 75.0
      for: 15m
      labels:
        severity: warning
    - alert: esphomeOvercurrent
      annotations:
        message: ESPHome node {{ $labels.name }} has {{ $value }} A of current.
      expr: |-
        esphome_sensor_value{unit="A"} > 2000
      labels:
        severity: warning
    - alert: esphomeRebooted
      annotations:
        message: ESPHome node {{ $labels.name }} had rebooted.
      expr: |-
        esphome_sensor_value{unit="s"} < 100
      labels:
        severity: warning
