---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tdarr
  labels:
    app: tdarr
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  iscsi:
    targetPortal: ${SECRET_STORAGE_ADDRESS}
    iqn: ${SECRET_STORAGE_IQN}:kube-tdarr
    lun: 1
    fsType: ext4
    readOnly: false
    chapAuthSession: true
    secretRef:
      name: storage-secret
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: tdarr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector: 
    matchLabels:
      app: tdarr
