---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: iot
resources:
- elgato2mqtt
- esphome
- home-assistant
- mosquitto
- network-monitoring
- node-red
- shared
# - zigbee2mqtt
