---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: speedtest-exporter
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: speedtest-exporter
      version: 5.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    # https://github.com/k8s-at-home/charts/blob/master/charts/stable/speedtest-exporter/values.yaml
    image:
      repository: ghcr.io/miguelndecarvalho/speedtest-exporter
      tag: v3.2.2
    env:
      TZ: "${SECRET_TIMEZONE}"
    metrics:
      enabled: true
      serviceMonitor:
        additionalLabels: 
          release: kube-prometheus-stack
      prometheusRule:
        enabled: true
        additionalLabels: 
          role: alert-rules
        downloadLimit: 1000
        uploadLimit: 100
        pingLimit: 10
        jitterLimit: 30
        labels:

        rules:
        - alert: SpeedtestSlowInternetDownload
          annotations:
            description: Internet download speed is averaging {{ "{{ humanize $value }}" }} Mbps.
            summary: SpeedTest slow internet download.
          expr: |
            avg_over_time(speedtest_download_bits_per_second{job=~".*{{ include "common.names.fullname" . }}.*"}[4h])
              < {{ .Values.metrics.prometheusRule.downloadLimit }}
          for: 0m
          labels:
            severity: warning
