---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: speedtest-exporter
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: speedtest-exporter
      version: 5.0.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    # https://github.com/k8s-at-home/charts/blob/master/charts/stable/speedtest-exporter/values.yaml
    image:
      repository: ghcr.io/miguelndecarvalho/speedtest-exporter
      tag: v3.2.2
    metrics:
      enabled: True
      serviceMonitor:
        labels:
          release: kube-prometheus-stack
