# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  SECRET_DOMAIN: ${BOOTSTRAP_DOMAIN}
  SECRET_LETS_ENCRYPT_EMAIL: ${SECRET_LETS_ENCRYPT_EMAIL}
