---
apiVersion: v1
kind: Secret
metadata:
  name: storage-secret
type: kubernetes.io/iscsi-chap
data:
  node.session.auth.username: ${SECRET_CHAP_USERNAME_BASE64}
  node.session.auth.password: ${SECRET_CHAP_PASSWORD_BASE64}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vaultwarden
  labels:
    app: vaultwarden
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  iscsi:
    targetPortal: ${SECRET_STORAGE_ADDRESS}
    iqn: ${SECRET_IQN}:kube-vaultwarden
    lun: 1
    fsType: ext4
    readOnly: false
    chapAuthSession: true
    secretRef:
      name: storage-secret
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: vaultwarden
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector: 
    matchLabels:
      app: vaultwarden
