---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vaultwarden
spec:
  interval: 5m
  releaseName: vaultwarden
  chart:
    spec:
      # renovate: registryUrl=https://gissilabs.github.io/charts/
      chart: vaultwarden
      version: 0.4.0
      sourceRef:
        kind: HelmRepository
        name: gissilabs-charts
        namespace: flux-system
  install:
    remediation:
      retries: 3

  values:
    # Focus on intel for now.
    nodeSelector:
      kubernetes.io/arch: amd64
    strategy: # Need to turn down then turn up (depend on one persistent volume)
      type: Recreate
    env:
      TZ: "${SECRET_TIMEZONE}"

    # Backup
    podAnnotations:
      backup.velero.io/backup-volumes: vaultwarden


    vaultwarden:
      domain: https://vault.${SECRET_DOMAIN}
      allowSignups: false
      showPasswordHint: false
      enableWebsockets: true
      yubico:
        enabled: true
        clientId: ${SECRET_VAULTWARDEN_CLIENTID}
        secretKey: ${SECRET_VAULTWARDEN_SECRETKEY}
    ingress:
      enabled: true
      host: vault.${SECRET_DOMAIN}
      tls:
      - hosts:
        - vault.${SECRET_DOMAIN}
        secretName: vaultwarden-tls
      annotations:
        kubernetes.io/ingress.class: "nginx"
        cert-manager.io/cluster-issuer: letsencrypt-production
    persistence:
      enabled: true
      size: "1Gi"
      existingClaim: vaultwarden
