apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - default # Disable to setup core.
  # - iot # Disabled to setup core.
  # - media # Disabled to setup core.
  - networking
