apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
- jackett
- plex
- radarr
- shared
- sonarr

patches:
- path: ./patch/base-helm.yaml
  target:
    kind: HelmRelease
