---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kdns
  labels:
    app: kdns
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: kdns
  template:
    metadata:
      labels:
        app: kdns
    spec:
      serviceAccount: kdns
      containers:
        - name: kdns
          image: cronuxs/kdns:v0.0.10
          args: ["/go/bin/kdns", "--externalDNS", "1.1.1.1,8.8.8.8", "--baseDomain", "${SECRET_DOMAIN}."]
          resources:
            requests:
              memory: "10Mi"
              cpu: "50m"
            limits:
              memory: "20Mi"
              cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: kdns-svc
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.6.222
  externalTrafficPolicy: Local
  ports:
    - name: dns
      targetPort: 5353
      port: 53
      protocol: UDP
  selector:
    app: kdns
