apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ingress-reader
rules:
- apiGroups: ["networking.k8s.io", ""]
  resources: ["ingresses", "services"]
  verbs: ["list", "get"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kdns
  namespace: networking
--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kdns-ingress-reader
roleRef:
  kind: ClusterRole
  name: ingress-reader
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: kdns
  namespace: networking
---