apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
  - helm-release.yaml
  - alerts.yaml
  # Moved to apps (race condition)
  # - letsencrypt-production.yaml
  # - letsencrypt-staging.yaml
