apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-monitoring
  labels:
    app: network-monitoring
spec:
  replicas: 1
  strategy:
    type: Recreate # Birth and Will messages make more sense
  selector:
    matchLabels:
      app: network-monitoring
  template:
    metadata:
      labels:
        app: network-monitoring
    spec:
      nodeSelector:
        role: iot-controller
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "iot"
        effect: "NoSchedule"
      containers:
      - name: network-monitoring
        image: cronuxs/network-monitoring:v0.1.2
        resources:
          requests:
            memory: "10Mi"
            cpu: "50m"
          limits:
            memory: "20Mi"
            cpu: "100m"
        volumeMounts:
        - mountPath: /config
          name: config
      volumes:
      - name: config
        configMap:
          name: network-monitoring-config
